# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 10:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='company',
        ),
        migrations.RemoveField(
            model_name='members',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='company',
            name='workers',
        ),
        migrations.AlterField(
            model_name='company',
            name='founded',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2018), django.core.validators.MinValueValidator(1800)], verbose_name='founded'),
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
